import { Schema, model } from 'mongoose';

const GuildSchema = new Schema({
  guildId:       { type: String, required: true, unique: true },
  prefix:        { type: String, default: '??' },
  setupComplete: { type: Boolean, default: false },
  caseCounter:   { type: Number, default: 0 },
  panicMode:     { type: Boolean, default: false },
  channels: {
    publicLogs:     String,
    modLogs:        String,
    serverLogs:     String,
    joinLogs:       String,
    welcomeChannel: String,
    goodbyeChannel: String,
    reportChannel:  String,
    appealChannel:  String,
    ticketCategory: String,
    battleChannel:  String,
  },
  roles: {
    modRoles:      [String],
    adminRoles:    [String],
    muteRole:      String,
    verifiedRole:  String,
    autoRoles:     [String],
    watchlistRole: String,
    appealRole:    String,
  },
  settings: {
    welcome: {
      enabled:   { type: Boolean, default: false },
      message:   String,
      useEmbed:  { type: Boolean, default: true },
      useBanner: { type: Boolean, default: true },
    },
    goodbye: {
      enabled: { type: Boolean, default: false },
      message: String,
    },
    autorole: { enabled: { type: Boolean, default: false } },
    verification: {
      enabled:        { type: Boolean, default: false },
      type:           { type: String, enum: ['button','captcha','reaction'], default: 'button' },
      panelMessageId: String,
      panelChannelId: String,
    },
    logging: {
      enabled:         { type: Boolean, default: true },
      ignoredChannels: [String],
      events: {
        messageDelete:  { type: Boolean, default: true },
        messageEdit:    { type: Boolean, default: true },
        memberJoin:     { type: Boolean, default: true },
        memberLeave:    { type: Boolean, default: true },
        memberBan:      { type: Boolean, default: true },
        memberUnban:    { type: Boolean, default: true },
        roleCreate:     { type: Boolean, default: true },
        roleDelete:     { type: Boolean, default: true },
        channelCreate:  { type: Boolean, default: true },
        channelDelete:  { type: Boolean, default: true },
        guildUpdate:    { type: Boolean, default: true },
        memberUpdate:   { type: Boolean, default: true },
        inviteCreate:   { type: Boolean, default: false },
        threadCreate:   { type: Boolean, default: false },
      },
    },
    automod: {
      enabled: { type: Boolean, default: false },
      antispam: {
        enabled:   { type: Boolean, default: false },
        threshold: { type: Number, default: 5 },
        interval:  { type: Number, default: 5000 },
        action:    { type: String, enum: ['delete','warn','mute','kick'], default: 'delete' },
      },
      antilink: {
        enabled:   { type: Boolean, default: false },
        whitelist: [String],
        action:    { type: String, enum: ['delete','warn','mute','kick'], default: 'delete' },
      },
      antinvite: {
        enabled: { type: Boolean, default: false },
        action:  { type: String, enum: ['delete','warn','mute'], default: 'delete' },
      },
      caps: {
        enabled:    { type: Boolean, default: false },
        percentage: { type: Number, default: 70 },
        minLength:  { type: Number, default: 10 },
        action:     { type: String, enum: ['delete','warn'], default: 'delete' },
      },
      mentionspam: {
        enabled:   { type: Boolean, default: false },
        threshold: { type: Number, default: 5 },
        action:    { type: String, enum: ['delete','warn','mute','kick'], default: 'warn' },
      },
      newaccount: {
        enabled: { type: Boolean, default: false },
        age:     { type: Number, default: 7 },
        action:  { type: String, enum: ['kick','ban','mute'], default: 'kick' },
      },
      badwords: { type: [String], default: [] },
    },
    antiraid: {
      enabled:       { type: Boolean, default: false },
      joinThreshold: { type: Number, default: 10 },
      joinInterval:  { type: Number, default: 10000 },
      action:        { type: String, enum: ['kick','ban','lockdown'], default: 'lockdown' },
    },
    antinuke: {
      enabled: { type: Boolean, default: false },
      thresholds: {
        banThreshold:           { type: Number, default: 3 },
        kickThreshold:          { type: Number, default: 3 },
        channelDeleteThreshold: { type: Number, default: 2 },
        roleDeleteThreshold:    { type: Number, default: 2 },
      },
      whitelist: [String],
      action: { type: String, enum: ['ban','kick','strip','deowner'], default: 'ban' },
    },
    tickets: {
      enabled:        { type: Boolean, default: false },
      panelMessageId: String,
      panelChannelId: String,
      supportRoles:   [String],
      maxTickets:     { type: Number, default: 1 },
      transcripts:    { type: Boolean, default: true },
      counter:        { type: Number, default: 0 },
    },
    battle: {
      enabled:         { type: Boolean, default: true },
      resultChannelId: String,
    },
    inviteTracking: { type: Boolean, default: false },
    compactMode:    { type: Boolean, default: false },
  },
  automodWhitelist: {
    channels: [String],
    roles:    [String],
    users:    [String],
  },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

export default model('Guild', GuildSchema);
